"""empty message

Revision ID: 3fed8757f20f
Revises: df69c727aefd
Create Date: 2021-01-13 15:57:36.035782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3fed8757f20f'
down_revision = 'df69c727aefd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('filename', sa.String(length=100), nullable=False))
    op.add_column('file', sa.Column('md5', sa.String(length=32), nullable=False))
    op.drop_column('file', 'file_name')
    op.drop_column('file', 'token')
    op.drop_column('file', 'sha384')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('sha384', mysql.VARCHAR(length=96), nullable=False))
    op.add_column('file', sa.Column('token', mysql.VARCHAR(length=300), nullable=False))
    op.add_column('file', sa.Column('file_name', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('file', 'md5')
    op.drop_column('file', 'filename')
    # ### end Alembic commands ###
