"""empty message

Revision ID: 5d1f7d5a6aab
Revises: b2d4bf659a60
Create Date: 2021-01-16 01:04:20.465235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d1f7d5a6aab'
down_revision = 'b2d4bf659a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('md5', sa.String(length=32), nullable=False),
    sa.Column('upload', sa.DateTime(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('md5'),
    sa.UniqueConstraint('md5')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    # ### end Alembic commands ###
