"""empty message

Revision ID: a7952c245ac1
Revises: eaffe47ed751
Create Date: 2021-03-09 01:13:59.232955

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7952c245ac1'
down_revision = 'eaffe47ed751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'service')
    op.drop_column('file', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('email', mysql.VARCHAR(length=96), nullable=True))
    op.add_column('file', sa.Column('service', mysql.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
