"""empty message

Revision ID: df69c727aefd
Revises: 
Create Date: 2021-01-13 12:38:42.400233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df69c727aefd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('idx', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=False),
    sa.Column('sha384', sa.String(length=96), nullable=False),
    sa.Column('token', sa.String(length=300), nullable=False),
    sa.Column('upload', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    # ### end Alembic commands ###
